version: '3.3'

services:

  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "4322:27017"

  fast_api:
    build: ./fast_api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./fast_api/:/app/
    depends_on:
      - mongo_db
    ports:
      - '8000:8000'
    restart: "always"

